{
 "title": "BigQuery Storage",
 "tags": [
  "BigQuery",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Stored Bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "bigquery.googleapis.com/storage/stored_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Number of Tables",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "bigquery.googleapis.com/storage/table_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Stored Bytes (Datasets)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [ "resource.label.dataset_id" ],
      "metricKind": "GAUGE",
      "metricType": "bigquery.googleapis.com/storage/stored_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Number of Tables (Datasets)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [ "resource.label.dataset_id" ],
      "metricKind": "GAUGE",
      "metricType": "bigquery.googleapis.com/storage/table_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}